version: "3"
vars:
  K3S_CONFIG: /etc/rancher/k3s/config.yaml
env:
  INSTALL_K3S_VERSION: v1.30.4+k3s1

silent: true

tasks:
  server:
    cmds:
    - |
      sudo curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="${INSTALL_K3S_VERSION}" INSTALL_K3S_EXEC="--disable=traefik --disable=servicelb" sh -s - -c {{.K3S_CONFIG}}
    ignore_error: true
    interactive: true
