apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - pihole.yaml
  - ingress-nginx.yaml
  - external-dns.yaml
namespace: argocd
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
