apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
spec:
  description: Networking related Kubernetes resources
  sourceRepos:
    - "*"
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: pihole-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
