apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cr.yaml
- crb.yaml
- deployment.yaml
- ingressclass.yaml
- svc.yaml
- sa.yaml
- role.yaml
- rb.yaml
- cm.yaml

namespace: kube-system
