apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/projects

  - base/core/argocd.yaml
  - base/core/networking.yaml

  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml

images:
- name: quay.io/argoproj/argocd
  newTag: v2.12.3

patches:
  - path: overlay/argocd-svc.yaml
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
      spec:
        type: LoadBalancer
